github: [ctkqiang]
patreon: ctkqiang
ko_fi: ctkqiang
custom:
  - https://donate.stripe.com/00gg2nefu6TK1LqeUY
  - https://qr.alipay.com/fkx19369scgxdrkv8mxso92
  - https://raw.githubusercontent.com/ctkqiang/ctkqiang/refs/heads/main/assets/IMG_9859.JPG
